### ISSUE TITLE
Combine update and download

### ISSUE THREAD

**Issue by mtfurlan** [ominitay/shellsaber#13]
To me it doesn't make sense to have separate update and download commands.
When I invoke shaber, I would like it to do whatever necessary to get the mods installed.
Is there some usecase I'm just completely overlooking that necessatates separated download/update?

### Describe the solution you'd like 
Combine update and download, or maybe just call the other one after the warning so you see
```
Warn: Mod 'BeatSaverDownloader' is already downloaded.
Info: Updating 'BeatSaverDownloader'
```
and vise versa for updating a not installed mod.

If we come to some agreement on how it should work I can do the PR if you want.

**Comment by ominitay** [comment]
In my opinion, I think that downloading and updating mods should be separate. For example, it makes more sense to use the command `shaber update all` to update mods, rather than the command `shaber download enabled; shaber download disabled`. Also, most people would go for the `update` command when intending to *update* their mods, rather than the `download` command. 

Overall, while technically feasible, I don't see a benefit to making this change. I'm open to being persuaded otherwise though :)
